import assert from 'node:assert/strict';
import {buildDebtPaymentTransactionMap,cashOutflowBase,consumptionExpenseBase,debtPrincipalBase,debtCostBase} from '../assets/js/app/financial-effects.js';
import {convertAmount} from '../assets/js/app/fx.js';
const fx={rates:{CHF:1,EUR:0.95,USD:0.8,GBP:1.1}};
const p={transaction_id:'t1',principal_amount:280,interest_amount:15,fee_amount:5,currency:'CHF',reversed_at:null};
const map=buildDebtPaymentTransactionMap([p]);
const debt={id:'t1',status:'booked',transfer_group_id:null,amount:-300,currency:'CHF',cashflow_type:'debt_payment'};
assert.equal(cashOutflowBase(debt,'CHF',fx),300);
assert.equal(consumptionExpenseBase(debt,map,'CHF',fx),20);
assert.equal(debtPrincipalBase(debt,map,'CHF',fx),280);
assert.equal(debtCostBase(debt,map,'CHF',fx),20);
const expense={id:'t2',status:'booked',transfer_group_id:null,amount:-100,currency:'CHF',cashflow_type:'standard'};
assert.equal(consumptionExpenseBase(expense,map,'CHF',fx),100);
const transfer={...expense,transfer_group_id:'g'};
assert.equal(consumptionExpenseBase(transfer,map,'CHF',fx),0);
const pending={...expense,status:'pending'};
assert.equal(consumptionExpenseBase(pending,map,'CHF',fx),0);
assert.equal(convertAmount(100,'EUR','CHF',fx),95);
assert.equal(convertAmount(95,'CHF','EUR',fx),100);
console.log('financial-effects assertions OK');
